language: cpp
compiler: g++

notifications:
  email: false

env:
 - GTEST_DIR=~/gtest/googletest-release-1.8.0/googletest

before_install:
 # Install a supported cmake version
 - mkdir -p ~/cmake
 - wget -O cmake.sh https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh 
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix="${HOME}/cmake"
 - export PATH=~/cmake/bin:$PATH
 - cmake --version
 # install google test
 - mkdir -p ~/gtest
 - cd ~/gtest
 - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0/googletest
 - cmake -DBUILD_SHARED_LIBS=ON .
 - make
 # target cmake requires ".a" OSX binaries
 - mkdir build
 - cp libgtest_main.so build/libgtest_main.a
 - cp libgtest.so build/libgtest.a
 # still needed to actually execute the binary
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/ 

script:
 - cd $TRAVIS_BUILD_DIR
 - mkdir build
 - cd build
 - cmake ../test/
 - make
 - ./unittest
